//import React from "react";

const pages = {
    ru: {

        table: "таблица",
        tree: "дерево",
        all: "всё",
        add: "добавить",
        edit: "редактировать",
        remove: "удалить",
        cancel: "отмена",
        save: "сохранить",
        id: "ID",
        title: "название",
        slug: "ссылка",
        desc: "описание",
        image: "изображение",
        parent: "родитель",
        noparent: "нет родителя",
        actions: "действия",
        add: "добавить",
        change: "изменить",
        saveChange: "сохранить изменение",
        remove: "удалить",
        selectImage: "выберите изображение",
        addCategory: "добавление категории",
        areYouSure: "Вы уверены!",
        categorySuccessAdd: "Категория успешно добавлена",
        categorySuccessDelete: "Категория успешно удалена",
        categorySuccessUpdate: "Изменение сохранено",
        old: "старый ",
        new: "новый ",
        category: "Категория",
        clients: "клиенты",
        partners: "партнёры",
        subscribers: "подписчики",
        users: "сотрудники",
        facebook: "facebook",
        instagram: "instagram",

        shop: {

            title: "Добавление продукта",
            subtitle: "продукт будет добавлен после оканчательново завершения",

            next: "дальше",
            prev: "предыдущий",
            finish: "Добавить продукт",
            required: "обязательный",

            step1: "Основная",
            step2: "Цена и кол-во",
            step3: "Атрибуты",
            step4: "Размеры",
            step5: "Дополнительное",

            info1: "Основная информация продукта",
            info2: "Цены, доступность и количество продукта",
            info3: "Атрибуты и описания продукта",
            info4: "",
            info5: "Дополнительная информация о продукте",

            name: "название",
            sku: "артикул (SKU)",
            barcode: "штрих код",
            category: "категория",

            tags: "теги",
            tag: "тег",
            addTags: "введите и нажмите ввод",
            defaultTags: ['новинка', 'new'],

            price1: "цена",
            price2: "цена (оптовая)",
            price3: "цена (для партнеров)",
            available: "наличие",
            availableProduct: "наличие продукта",
            true: "доступно",
            false: "нет в наличии",
            soon: "скоро",
            order: "по заказу",
            count: "кол-во (штук) на складе",
            countReserve: "из них (штук) в резерве",
            brend: "производитель",
            newBrend: "введите новую марку производителя",
            brendCountry: "страна производителя",
            chooseBrend: "выберите производителя",
            chooseBrendCountry: "выберите страну производителя",
            model: "модель",
            material: "материал",
            chooseMaterial: "выберите материал",
            newMaterial: "введите новый вид материала",
            color: "цвет",
            chooseColor: "выберите цвет",
            newColor: "введите новый цвет",
            specific: "характеристика",
            desc: "описание",
            gross: "брутто",
            net: "нетто",
            weight: "вес",
            piece1: "1 штук",
            piece: "штук",
            box: "коробка",
            size: "размер",
            sizeA: "длина",
            sizeB: "ширина",
            sizeH: "высота",
            mm: "мм",
            g: "грамм",
            kg: "кг",
            sizeWithOut: "размер (без упаковки)",
            weightWithOut: "вес (без упаковки)",
            sizeWith: "размер (с упаковкой)",
            countInPack: "кол-во штук в 1 упаковке",
            countInBox: "кол-во в упаковк 1 ящике",
            pack: "упаковка",
            validationMsg: "это поле не может быть пустым",
        }
    }
}

export { pages };

